version: '3.3'

services:
  app:
    build: services/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/app/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.app.env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./services/db/data:/var/lib/postgresql/data
    env_file:
      - ./.db.env

