#! /usr/bin/env bash
# vim: filetype=sh syntax=sh

set -euo pipefail

source "${TMPL_SCRIPT_INCLUDE_DIR}/tmpl"
source "${TMPL_SCRIPT_INCLUDE_DIR}/diagnostics"
source "${TMPL_SCRIPT_INCLUDE_DIR}/checks"

_target_dir="$TMPL_OUTPUT_DIR"

cp -iR "${TMPL_TYPE_DIR}/templates/"** "$TMPL_OUTPUT_DIR"

