#! /usr/bin/env bash
# vim: filetype=sh syntax=sh

set -euo pipefail

source "${TMPL_SCRIPT_INCLUDE_DIR}/tmpl"
source "${TMPL_SCRIPT_INCLUDE_DIR}/diagnostics"

_tmpl_cmake_template='CMakeLists.txt'
_tmpl_cmake_default_project_name='myproject'
_tmpl_cmake_target_file="${TMPL_OUTPUT_DIR}/${_tmpl_cmake_template}"

tmpl_error_if_placeholders

if [[ -e "$_tmpl_cmake_target_file" ]]
then
  tmpl_skip_info "$_tmpl_cmake_target_file"
  exit
fi

tmpl_mkdir_if_not_exists "$TMPL_OUTPUT_DIR"

tmpl_process_templates \
  --define=TMPL_CMAKE_NAME="${1-$_tmpl_cmake_default_project_name}" \
  "${TMPL_TYPE_DIR}/templates/${_tmpl_cmake_template}" \
  > "$_tmpl_cmake_target_file"

